nelmio_api_doc:
    use_validation_groups: true
    documentation:
        info:
            title: Produkte Verwaltung
            description: Max sein Projekt für den ük 295
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/docs$) # Accepts routes under /api except /api/docs
